AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Double-Barrel Shotgun"
SWEP.Purpose = "An old time-honoured double-barrel shotgun, though it holds 2 rounds, its power is the envy of any shotgun... (No)"
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Category = "! Forsakened"
SWEP.Spawnable = true
SWEP.UseHands = true
SWEP.Primary.ClipSize = 2
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/tfa_nmrih/v_fa_sv10.mdl")
SWEP.WorldModel = Model("models/weapons/tfa_nmrih/w_fa_sv10.mdl")
SWEP.IdlePos = Vector(0, -8, 0)
SWEP.ViewModelFOV = 110
SWEP.InsHands = false
SWEP.ViewModelFlip = false
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = 11
SWEP.FuckedWorldModelUp = 1
SWEP.FuckedWorldModelRight = 0.5
SWEP.FuckedWorldModelAngFW = 180
SWEP.FuckedWorldModelAngR = -10
SWEP.Primary.Ammo = "Buckshot"
SWEP.Primary.Damage = 50
SWEP.Primary.NumShots = 8
SWEP.Primary.Recoil = 3.5
SWEP.ShellType = ""
SWEP.TriggerDelay = .06
SWEP.CycleTime = .2
SWEP.Primary.Automatic = false
SWEP.ENT = "mann_ent_db"
SWEP.CustomColor = Color(200, 200, 150, 255)
SWEP.HolsterSlot = 3
SWEP.AimPos = Vector(-3.65, 3.5, -1)
SWEP.AimAng = Angle(0, 0.9, 0)
SWEP.SprintPos = Vector(9, 2, -3)
SWEP.SprintAng = Angle(0, 50, 0)
SWEP.CloseFireSound = Sound("weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_fire1.wav")
SWEP.ExtraFireSound = Sound("snd_mann_bulletcrack.wav")
SWEP.FarFireSound = Sound("weapons/firearms/shtg_berettasv10/beretta_fire_01.wav")
SWEP.ReloadSound = Sound("weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_open.wav")
SWEP.ShotPitch = math.random(95, 100)
SWEP.DrawAnim = "draw"
SWEP.FireAnim = "fire"
SWEP.LastFireAnim = "fire_last"
SWEP.DryFireAnim = "fire_dry"
SWEP.ReloadAnim = "reload_empty"
SWEP.ReloadTime = 4.4
SWEP.ReloadRate = 1.2
SWEP.HipHoldType = "alaln_rifle_idle"
SWEP.AimHoldType = "alaln_rifle_aim"
SWEP.DownHoldType = "passive"
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.BarrelLength = 8
SWEP.Droppable = true