AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Glock-17"
SWEP.Purpose = "A gun that has survived many gangster shootouts and more. Despite this, it is still an excellent tool for cleansing the world of evil."
SWEP.Instructions = "LMB to fire,\nRMB to aim sights.\n\nUnlike a lighter, there's no catch. You can safely put it in your pocket without a safety."
SWEP.Spawnable = true
SWEP.Category = "! Forsakened"
SWEP.Spawnable = true
SWEP.Primary.ClipSize = 17
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/tfa_nmrih/v_fa_glock17.mdl")
SWEP.WorldModel = Model("models/weapons/tfa_nmrih/w_fa_glock17.mdl")
SWEP.IdlePos = Vector(0, -7, 0)
SWEP.ViewModelFOV = 120
SWEP.ViewModelFlip = false
SWEP.InsHands = false
SWEP.UseHands = true
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = 3
SWEP.FuckedWorldModelUp = -4
SWEP.FuckedWorldModelRight = 1.5
SWEP.Primary.Ammo = "Pistol"
SWEP.Primary.Damage = 50
SWEP.Primary.Recoil = 2.2
SWEP.ShellType = "ShellEject"
SWEP.Primary.Automatic = false
SWEP.TriggerDelay = .1
SWEP.CycleTime = .06
SWEP.ENT = "mann_ent_g17"
SWEP.CustomColor = Color(150, 150, 150, 255)
SWEP.HolsterSlot = 2
SWEP.AimPos = Vector(-2.4, -2, 0.8)
SWEP.AimAng = Angle(0.75, 1, 0)
SWEP.SprintPos = Vector(5, 2, 0)
SWEP.SprintAng = Angle(-20, 30, 0)
SWEP.CloseFireSound = Sound("weapons/firearms/hndg_glock17/glock_fire_01older.wav")
SWEP.ExtraFireSound = Sound("weapons/357_fire2.wav")
SWEP.FarFireSound = Sound("weapons/firearms/hndg_glock17/glock_fire_01old.wav")
SWEP.ReloadSound = Sound("snd_mann_rifle_reload.wav")
SWEP.ShotPitch = math.random(95, 103)
SWEP.DrawAnim = "draw_first"
SWEP.FireAnim = "fire"
SWEP.DryFireAnim = "fire_empty"
SWEP.ReloadAnim = "reload_dry"
SWEP.ReloadTime = 2.4
SWEP.ReloadRate = .75
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.Droppable = true