AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Mosin Nagant M91"
SWEP.Purpose = "A very old but popular Russian long-range rifle, used by both the Tsarist Army and the Soviet Army, has nevertheless survived to the present day, and is now used only by desperate survivors who still have hope in this world."
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Spawnable = true
SWEP.Category = "! Forsakened"
SWEP.Spawnable = true
SWEP.Primary.ClipSize = 5
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/c_ins2_mosin_nagant.mdl")
SWEP.WorldModel = Model("models/weapons/w_ins2_mosin_nagant.mdl")
SWEP.IdlePos = Vector(0, -4, -1)
SWEP.ViewModelFOV = 90
SWEP.ViewModelFlip = false
SWEP.InsHands = false
SWEP.UseHands = true
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = 2
SWEP.FuckedWorldModelUp = 0
SWEP.FuckedWorldModelRight = 0.5
SWEP.FuckedWorldModelAngFW = 180
SWEP.FuckedWorldModelAngR = -5
SWEP.Primary.Ammo = "SniperRound"
SWEP.Primary.Damage = 110
SWEP.Primary.Recoil = 4.1
SWEP.ShellType = ""
SWEP.Primary.Automatic = false
SWEP.TriggerDelay = .1
SWEP.CycleTime = 1.4
SWEP.CycleType = "manual"
SWEP.ReloadType = "individual"
SWEP.ENT = "mann_ent_mosin"
SWEP.CustomColor = Color(150, 150, 150, 255)
SWEP.HolsterSlot = 3
SWEP.AimPos = Vector(-3.1, -2, 2)
SWEP.AimAng = Angle(0, 0.5, 0)
SWEP.SprintPos = Vector(7, 5, 4)
SWEP.SprintAng = Angle(-20, 30, 0)
SWEP.CloseFireSound = Sound("weapons/firearms/rifle_win1892/win1892_fire_01.wav")
SWEP.ExtraFireSound = Sound("snd_mann_bulletcrack.wav")
SWEP.FarFireSound = Sound("weapons/firearms/rifle_ruger1022/ruger_fire_01old.wav")
SWEP.ReloadSound = Sound("weapons/firearms/rifle_sks/sks_slideback.wav")
SWEP.ShotPitch = math.random(95, 103)
SWEP.DrawAnim = "base_draw"
SWEP.FireAnim = "base_fire_start"
SWEP.DryFireAnim = "base_dryfire"
SWEP.ReloadAnim = "reload_start"
SWEP.InsertAnim = "reload_insert"
SWEP.AfterReloadAnim = "reload_end"
SWEP.CycleAnim = "base_fire_end"
SWEP.CycleSound = "weapons/firearms/rifle_sako85/sako_boltopen.wav"
SWEP.ReloadTime = 3.6
SWEP.ReloadRate = .9
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.HipHoldType = "alaln_rifle_idle"
SWEP.AimHoldType = "alaln_rifle_aim"
SWEP.DownHoldType = "passive"
SWEP.BarrelLength = 10
SWEP.Droppable = true