AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Smith & Wesson Model 686"
SWEP.Purpose = "Что может делать револьвер? Срать в лицо!" --!!
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Spawnable = true
SWEP.Category = "Forsakened"
SWEP.Spawnable = true
SWEP.Primary.ClipSize = 6
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/tfa_nmrih/v_fa_sw686.mdl")
SWEP.WorldModel = Model("models/weapons/tfa_nmrih/w_fa_sw686.mdl")
SWEP.ViewModelFOV = 70
SWEP.ViewModelFlip = false
SWEP.InsHands = false
SWEP.UseHands = true
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = -3
SWEP.FuckedWorldModelUp = -2
SWEP.FuckedWorldModelRight = 2
SWEP.Primary.Ammo = "357"
SWEP.Primary.Damage = 90
SWEP.Primary.Recoil = 3.5
SWEP.ShellType = ""
SWEP.Primary.Automatic = false
SWEP.TriggerDelay = .1
SWEP.CycleTime = .4
SWEP.ENT = "mann_ent_sw686"
SWEP.CustomColor = Color(150, 150, 150, 255)
SWEP.HolsterSlot = 2
SWEP.AimPos = Vector(-2.5, -2, 1)
SWEP.AimAng = angle_zero
SWEP.SprintPos = Vector(5, -2, 0)
SWEP.SprintAng = Angle(-20, 30, 0)
SWEP.CloseFireSound = Sound("weapons/firearms/hndg_sw686/revolver_fire_01.wav")
SWEP.ExtraFireSound = Sound("weapons/357_fire2.wav")
SWEP.FarFireSound = Sound("weapons/firearms/hndg_sw686/revolver_fire_01old.wav")
SWEP.ReloadSound = ""
SWEP.ShotPitch = math.random(95, 103)
SWEP.DrawAnim = "draw"
SWEP.FireAnim = "fire"
SWEP.DryFireAnim = "fire_empty"
SWEP.ReloadAnim = "reload_dry"
SWEP.ReloadTime = 3.5
SWEP.ReloadRate = .9
SWEP.HipHoldType = "revolver"
SWEP.AimHoldType = "revolver"
SWEP.DownHoldType = "normal"
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.BarrelLength = 2
SWEP.Droppable = true