if SERVER then AddCSLuaFile() end
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Izmash AKM"
SWEP.Purpose = "Unlike the Glock, this gun hasn't fully survived the hardships. But in spite of that, somehow it still shoots."
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Category = "Forsakened"
SWEP.Spawnable = true
SWEP.UseHands = true
SWEP.Primary.ClipSize = 30
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/tfa_ins2/c_akm_bw.mdl")
SWEP.WorldModel = Model("models/weapons/tfa_ins2/w_akm_bw.mdl")
SWEP.ViewModelFOV = 75
SWEP.InsHands = true
SWEP.ViewModelFlip = false
SWEP.FuckedWorldModel = true
SWEP.Primary.Ammo = "AR2"
SWEP.Primary.Damage = 55
SWEP.Primary.Recoil = 1.5
SWEP.ShellType = "RifleShellEject"
SWEP.TriggerDelay = .06
SWEP.CycleTime = .05
SWEP.Primary.Automatic = true
SWEP.ENT = "mann_ent_akm"
SWEP.CustomColor = Color(200, 200, 200, 255)
SWEP.HolsterSlot = 3
SWEP.AimPos = Vector(-2.94, -2, 2)
SWEP.AimAng = angle_zero
SWEP.SprintPos = Vector(6, 0, -3)
SWEP.SprintAng = Angle(0, 50, 0)
SWEP.CloseFireSound = "weapons/firearms/rifle_cz858/cz858_fire_01.wav"
SWEP.ExtraFireSound = "weapons/357_fire2.wav"
SWEP.FarFireSound = "weapons/firearms/rifle_cz858/cz858_fire_01old.wav"
SWEP.ReloadSound = "snd_mann_rifle_reload.wav"
SWEP.ShotPitch = math.random(95, 100)
SWEP.DrawAnim = "base_draw"
SWEP.FireAnim = "base_fire"
SWEP.DryFireAnim = "base_dryfire"
SWEP.ReloadAnim = "base_reload"
SWEP.ReloadTime = 3.5
SWEP.ReloadRate = 1
SWEP.HipHoldType = "shotgun"
SWEP.AimHoldType = "rpg"
SWEP.DownHoldType = "passive"
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.BarrelLength = 6