AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Sudaev PPS-43"
SWEP.Purpose = "An old Soviet submachine gun, not as popular as the PPSh, but still good for its time. Loaded with 35 rounds of 7.62 caliber ammunition, it has a large and unstable recoil, but it is good for close combat in confined spaces."
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Category = "! Forsakened"
SWEP.Spawnable = true
SWEP.UseHands = true
SWEP.Primary.ClipSize = 35
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/v_models/v_pps43_5a.mdl")
SWEP.WorldModel = Model("models/w_models/weapons/w_smg_a.mdl")
SWEP.IdlePos = Vector(0, -6, 0)
SWEP.ViewModelFOV = 110
SWEP.InsHands = true
SWEP.ViewModelFlip = false
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = 0.5
SWEP.FuckedWorldModelUp = 0.5
SWEP.Primary.Ammo = "pistol"
SWEP.Primary.Damage = 25
SWEP.Primary.Recoil = 1.2
SWEP.ShellType = "ShellEject"
SWEP.TriggerDelay = .035
SWEP.CycleTime = .05
SWEP.Primary.Automatic = true
SWEP.ENT = "mann_ent_pps43"
SWEP.CustomColor = Color(200, 200, 200, 255)
SWEP.HolsterSlot = 3
SWEP.AimPos = Vector(-2, 0, 0.15)
SWEP.AimAng = Angle(0, 0.7, 0)
SWEP.SprintPos = Vector(8, 2, -3)
SWEP.SprintAng = Angle(0, 50, 0)
SWEP.CloseFireSound = Sound("weapons/firearms/rifle_cz858/cz858_fire_01.wav")
SWEP.ExtraFireSound = Sound("snd_mann_bulletcrack.wav")
SWEP.FarFireSound = Sound("weapons/firearms/rifle_cz858/cz858_fire_01old.wav")
SWEP.ReloadSound = Sound("snd_mann_rifle_reload.wav")
SWEP.ShotPitch = math.random(95, 100)
SWEP.DrawAnim = "base_draw"
SWEP.FireAnim = "base_fire"
SWEP.DryFireAnim = "base_dryfire"
SWEP.ReloadAnim = "base_reload"
SWEP.ReloadTime = 3.5
SWEP.ReloadRate = 0.9
SWEP.HipHoldType = "alaln_smg_idle"
SWEP.AimHoldType = "alaln_smg_aim"
SWEP.DownHoldType = "passive"
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.BarrelLength = 8
SWEP.Droppable = true