AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Sako 85 Sporter Rifle"
SWEP.Purpose = "PLACEHOLDER" --!!
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Spawnable = true
SWEP.Category = "Forsakened"
SWEP.Spawnable = true
SWEP.Primary.ClipSize = 5
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/tfa_nmrih/v_fa_sako85_ironsights.mdl")
SWEP.WorldModel = Model("models/weapons/tfa_nmrih/w_fa_sako85_ironsights.mdl")
SWEP.ViewModelFOV = 50
SWEP.ViewModelFlip = false
SWEP.InsHands = false
SWEP.UseHands = true
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = 3
SWEP.FuckedWorldModelUp = -1.5
SWEP.Primary.Ammo = "357"
SWEP.Primary.Damage = 110
SWEP.Primary.Recoil = 4.1
SWEP.ShellType = ""
SWEP.Primary.Automatic = false
SWEP.TriggerDelay = .1
SWEP.CycleTime = 1.92
SWEP.ENT = "mann_ent_sako85"
SWEP.CustomColor = Color(150, 150, 150, 255)
SWEP.HolsterSlot = 3
SWEP.AimPos = Vector(-3.5, 2, 0.5)
SWEP.AimAng = angle_zero
SWEP.SprintPos = Vector(5, 0, 0)
SWEP.SprintAng = Angle(-20, 30, 0)
SWEP.CloseFireSound = Sound("weapons/firearms/hndg_sw686/revolver_fire_01.wav")
SWEP.ExtraFireSound = Sound("weapons/357_fire2.wav")
SWEP.FarFireSound = Sound("weapons/firearms/hndg_sw686/revolver_fire_01old.wav")
SWEP.ReloadSound = ""
SWEP.ShotPitch = math.random(95, 103)
SWEP.DrawAnim = "draw"
SWEP.FireAnim = "fire"
SWEP.DryFireAnim = "fire_empty"
SWEP.ReloadAnim = "reload_dry"
SWEP.ReloadTime = 3.55
SWEP.ReloadRate = .9
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.HipHoldType = "shotgun"
SWEP.AimHoldType = "rpg"
SWEP.DownHoldType = "passive"
SWEP.BarrelLength = 6
SWEP.Droppable = true