AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Kalashnikov AKM"
SWEP.Purpose = "Unlike the Glock, this gun hasn't fully survived the hardships. But in spite of that, somehow it still shoots."
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Category = "! Forsakened"
SWEP.Spawnable = true
SWEP.UseHands = true
SWEP.Primary.ClipSize = 30
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/tfa_ins2/c_akm_bw.mdl")
SWEP.WorldModel = Model("models/weapons/tfa_ins2/w_akm_bw.mdl")
SWEP.IdlePos = Vector(0, -6, 0)
SWEP.ViewModelFOV = 110
SWEP.InsHands = true
SWEP.ViewModelFlip = false
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = 4
SWEP.FuckedWorldModelUp = 1
SWEP.FuckedWorldModelRight = 0.5
SWEP.FuckedWorldModelAngFW = 180
SWEP.FuckedWorldModelAngR = -10
SWEP.Primary.Ammo = "AR2"
SWEP.Primary.Damage = 40
SWEP.Primary.Recoil = 1.8
SWEP.ShellType = "RifleShellEject"
SWEP.TriggerDelay = .09
SWEP.CycleTime = .05
SWEP.Primary.Automatic = true
SWEP.ENT = "mann_ent_akm"
SWEP.CustomColor = Color(200, 200, 200, 255)
SWEP.HolsterSlot = 3
SWEP.AimPos = Vector(-2.84, -2, 0.75)
SWEP.AimAng = Angle(0, 1.05, 0)
SWEP.SprintPos = Vector(6, 4, -3)
SWEP.SprintAng = Angle(0, 50, 0)
SWEP.CloseFireSound = Sound("weapons/firearms/rifle_cz858/cz858_fire_01.wav")
SWEP.ExtraFireSound = Sound("snd_mann_bulletcrack.wav")
SWEP.FarFireSound = Sound("weapons/firearms/rifle_cz858/cz858_fire_01old.wav")
SWEP.ReloadSound = Sound("snd_mann_rifle_reload.wav")
SWEP.ShotPitch = math.random(95, 100)
SWEP.DrawAnim = "base_draw"
SWEP.FireAnim = "base_fire"
SWEP.DryFireAnim = "base_dryfire"
SWEP.ReloadAnim = "base_reload"
SWEP.ReloadTime = 3.5
SWEP.ReloadRate = 0.8
SWEP.HipHoldType = "alaln_rifle_idle"
SWEP.AimHoldType = "alaln_rifle_aim"
SWEP.DownHoldType = "passive"
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.BarrelLength = 8
SWEP.Droppable = true