if SERVER then AddCSLuaFile() end
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Double-Barrel Shotgun"
SWEP.Purpose = "An old time-honoured double-barrel shotgun, though it holds 2 rounds, its power is the envy of any shotgun... (No)"
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Category = "Forsakened"
SWEP.Spawnable = true
SWEP.UseHands = true
SWEP.Primary.ClipSize = 2
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/tfa_nmrih/v_fa_sv10.mdl")
SWEP.WorldModel = Model("models/weapons/tfa_nmrih/w_fa_sv10.mdl")
SWEP.ViewModelFOV = 60
SWEP.InsHands = false
SWEP.ViewModelFlip = false
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = 10
SWEP.FuckedWorldModelUp = -3
SWEP.Primary.Ammo = "buckshot"
SWEP.Primary.Damage = 60
SWEP.Primary.NumShots = 8
SWEP.Primary.Recoil = 3.5
SWEP.ShellType = "RifleShellEject"
SWEP.TriggerDelay = .06
SWEP.CycleTime = .05
SWEP.Primary.Automatic = false
SWEP.ENT = "mann_ent_db"
SWEP.CustomColor = Color(200, 200, 150, 255)
SWEP.HolsterSlot = 3
SWEP.AimPos = Vector(-3.55, 2.5, 2.5)
SWEP.AimAng = angle_zero
SWEP.SprintPos = Vector(6, 0, -3)
SWEP.SprintAng = Angle(0, 50, 0)
SWEP.CloseFireSound = "weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_fire1.wav"
SWEP.ExtraFireSound = "weapons/357_fire2.wav"
SWEP.FarFireSound = "weapons/firearms/shtg_berettasv10/beretta_fire_01.wav"
SWEP.ReloadSound = "weapons/firearms/shtg_berettasv10/shotgun_doublebarrel_open.wav"
SWEP.ShotPitch = math.random(95, 100)
SWEP.DrawAnim = "draw"
SWEP.FireAnim = "fire"
SWEP.DryFireAnim = "fire_dry"
SWEP.ReloadAnim = "reload_empty"
SWEP.ReloadTime = 4.4
SWEP.ReloadRate = 1.2
SWEP.HipHoldType = "shotgun"
SWEP.AimHoldType = "rpg"
SWEP.DownHoldType = "passive"
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.BarrelLength = 5