AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "PPS-43"
SWEP.Purpose = "PLACEHOLDER"
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Category = "Forsakened"
SWEP.Spawnable = true
SWEP.UseHands = true
SWEP.Primary.ClipSize = 35
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/v_models/v_pps43_5a.mdl")
SWEP.WorldModel = Model("models/w_models/weapons/w_smg_a.mdl")
SWEP.ViewModelFOV = 75
SWEP.InsHands = true
SWEP.ViewModelFlip = false
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = 1.5
SWEP.FuckedWorldModelUp = -0.5
SWEP.Primary.Ammo = "pistol"
SWEP.Primary.Damage = 30
SWEP.Primary.Recoil = 1.2
SWEP.ShellType = "RifleShellEject"
SWEP.TriggerDelay = .035
SWEP.CycleTime = .05
SWEP.Primary.Automatic = true
SWEP.ENT = "mann_ent_akm"
SWEP.CustomColor = Color(200, 200, 200, 255)
SWEP.HolsterSlot = 3
SWEP.AimPos = Vector(-2.025, 0, 0.5)
SWEP.AimAng = angle_zero
SWEP.SprintPos = Vector(6, 0, -3)
SWEP.SprintAng = Angle(0, 50, 0)
SWEP.CloseFireSound = "weapons/firearms/rifle_cz858/cz858_fire_01.wav"
SWEP.ExtraFireSound = "weapons/357_fire2.wav"
SWEP.FarFireSound = "weapons/firearms/rifle_cz858/cz858_fire_01old.wav"
SWEP.ReloadSound = "snd_mann_rifle_reload.wav"
SWEP.ShotPitch = math.random(95, 100)
SWEP.DrawAnim = "base_draw"
SWEP.FireAnim = "base_fire"
SWEP.DryFireAnim = "base_dryfire"
SWEP.ReloadAnim = "base_reload"
SWEP.ReloadTime = 3.5
SWEP.ReloadRate = 1
SWEP.HipHoldType = "smg"
SWEP.AimHoldType = "rpg"
SWEP.DownHoldType = "passive"
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.BarrelLength = 6