AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Colt M1911"
SWEP.Purpose = "An old reliable gun" --!!
SWEP.Instructions = "LMB to fire,\nRMB to aim sights.\n\nUnlike a lighter, there's no catch. You can safely put it in your pocket without a safety."
SWEP.Spawnable = true
SWEP.Category = "Forsakened"
SWEP.Spawnable = true
SWEP.Primary.ClipSize = 7
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/tfa_doi/v_m1911.mdl")
SWEP.WorldModel = Model("models/weapons/tfa_doi/w_m1911.mdl")
SWEP.ViewModelFOV = 75
SWEP.ViewModelFlip = false
SWEP.InsHands = false
SWEP.UseHands = true
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = 4
SWEP.FuckedWorldModelUp = 2.2
SWEP.FuckedWorldModelRight = 1.8
SWEP.Primary.Ammo = "Pistol"
SWEP.Primary.Damage = 65
SWEP.Primary.Recoil = 2.2
SWEP.ShellType = "ShellEject"
SWEP.Primary.Automatic = false
SWEP.TriggerDelay = .1
SWEP.CycleTime = .07
SWEP.ENT = "mann_ent_m1911"
SWEP.CustomColor = Color(200, 200, 150, 255)
SWEP.HolsterSlot = 2
SWEP.AimPos = Vector(-1.85, -4, 0.35)
SWEP.AimAng = Angle(0.75, 0.5, 0)
SWEP.SprintPos = Vector(5, -2, 0)
SWEP.SprintAng = Angle(-20, 30, 0)
SWEP.CloseFireSound = Sound("weapons/firearms/hndg_colt1911/colt_1911_fire1.wav")
SWEP.ExtraFireSound = Sound("weapons/357_fire2.wav")
SWEP.FarFireSound = Sound("weapons/firearms/hndg_mkiii/mkiii_fire_01.wav")
SWEP.ReloadSound = Sound("snd_mann_rifle_reload.wav")
SWEP.ShotPitch = math.random(95, 103)
SWEP.DrawAnim = "base_draw"
SWEP.FireAnim = "base_fire"
SWEP.DryFireAnim = "base_dryfire"
SWEP.ReloadAnim = "base_reloadempty"
SWEP.ReloadTime = 3
SWEP.ReloadRate = .9
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.Droppable = true