AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Smith & Wesson Model 686"
SWEP.Purpose = "The popular six-shot revolver, previously used for hunting large animals, is now used by you to survive from half-dead psychopaths."
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Spawnable = true
SWEP.Category = "! Forsakened"
SWEP.Spawnable = true
SWEP.Primary.ClipSize = 6
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/tfa_nmrih/v_fa_sw686.mdl")
SWEP.WorldModel = Model("models/weapons/tfa_nmrih/w_fa_sw686.mdl")
SWEP.IdlePos = Vector(0, -8, 0)
SWEP.ViewModelFOV = 110
SWEP.ViewModelFlip = false
SWEP.InsHands = false
SWEP.UseHands = true
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = -3
SWEP.FuckedWorldModelUp = -1
SWEP.FuckedWorldModelRight = 2
SWEP.Primary.Ammo = "357"
SWEP.Primary.Damage = 80
SWEP.Primary.Recoil = 3.5
SWEP.ShellType = ""
SWEP.Primary.Automatic = false
SWEP.TriggerDelay = .1
SWEP.CycleTime = .4
SWEP.ENT = "mann_ent_sw686"
SWEP.CustomColor = Color(150, 150, 150, 255)
SWEP.HolsterSlot = 2
SWEP.AimPos = Vector(-2.3, -2, 0.8)
SWEP.AimAng = Angle(0, 0.7, 0)
SWEP.SprintPos = Vector(5, -2, 0)
SWEP.SprintAng = Angle(-20, 30, 0)
SWEP.CloseFireSound = Sound("weapons/firearms/hndg_sw686/revolver_fire_01.wav")
SWEP.ExtraFireSound = Sound("snd_mann_bulletcrack.wav")
SWEP.FarFireSound = Sound("weapons/firearms/hndg_sw686/revolver_fire_01old.wav")
SWEP.ReloadSound = Sound("snd_jack_hmcd_rvreload.wav")
SWEP.ShotPitch = math.random(95, 103)
SWEP.DrawAnim = "draw"
SWEP.FireAnim = "fire"
SWEP.LastFireAnim = "fire_last"
SWEP.DryFireAnim = "fire_empty"
SWEP.ReloadAnim = "reload_dry"
SWEP.ReloadTime = 3.7
SWEP.ReloadRate = 0.75
SWEP.HipHoldType = "alaln_revolver_idle"
SWEP.AimHoldType = "alaln_revolver_aim"
SWEP.DownHoldType = "alaln_melee"
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.BarrelLength = 5
SWEP.Droppable = true