AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Makarov PM"
SWEP.Purpose = "An old Makarov pistol from 1951 used by the soviet militia. Can still kick the ass of various not-so-living bastards."
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Category = "Forsakened"
SWEP.Spawnable = true
SWEP.UseHands = true
SWEP.Primary.ClipSize = 8
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/tfa_ins2/c_pm.mdl")
SWEP.WorldModel = Model("models/weapons/tfa_ins2/w_pm.mdl")
SWEP.ViewModelFOV = 75
SWEP.InsHands = true
SWEP.ViewModelFlip = false
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = 4
SWEP.FuckedWorldModelUp = -2
SWEP.Primary.Ammo = "pistol"
SWEP.Primary.Damage = 30
SWEP.Primary.Recoil = 1.5
SWEP.ShellType = "ShellEject"
SWEP.TriggerDelay = .06
SWEP.CycleTime = .05
SWEP.Primary.Automatic = false
SWEP.ENT = "mann_ent_pm"
SWEP.CustomColor = Color(200, 200, 150, 255)
SWEP.HolsterSlot = 2
SWEP.AimPos = Vector(-2.20, 0, 0.3)
SWEP.AimAng = angle_zero
SWEP.SprintPos = Vector(5, -2, 0)
SWEP.SprintAng = Angle(-20, 30, 0)
SWEP.CloseFireSound = "weapons/firearms/hndg_mkiii/mkiii_fire_01.wav"
SWEP.ExtraFireSound = "weapons/357_fire2.wav"
SWEP.FarFireSound = "weapons/firearms/hndg_glock17/glock_fire_01old.wav"
SWEP.ReloadSound = "snd_mann_pistol_reload1.wav"
SWEP.ShotPitch = math.random(95, 100)
SWEP.DrawAnim = "base_draw"
SWEP.FireAnim = "base_fire"
SWEP.DryFireAnim = "base_dryfire"
SWEP.ReloadAnim = "base_reload"
SWEP.ReloadTime = 3.5
SWEP.ReloadRate = 1
SWEP.HipHoldType = "pistol"
SWEP.AimHoldType = "revolver"
SWEP.DownHoldType = "normal"
SWEP.IconOverride = "editor/ai_goal_standoff"