AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Stoner M16"
SWEP.Purpose = "Standard-issue semi-automatic rifle M16 with a recoil compensating grip, earlier used by army and special forces, now “purifiers” exterminate the rest of the world with it."
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Category = "! Forsakened"
SWEP.Spawnable = true
SWEP.UseHands = true
SWEP.Primary.ClipSize = 30
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/tfa_nmrih/v_fa_m16a4.mdl")
SWEP.WorldModel = Model("models/weapons/tfa_nmrih/w_fa_m16a4.mdl")
SWEP.IdlePos = Vector(-1, -6, -1)
SWEP.ViewModelFOV = 110
SWEP.InsHands = true
SWEP.ViewModelFlip = false
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = -1
SWEP.FuckedWorldModelUp = -1
SWEP.FuckedWorldModelRight = 2.5
SWEP.Primary.Ammo = "AR2"
SWEP.Primary.Damage = 35
SWEP.Primary.Recoil = 2.3
SWEP.ShellType = "RifleShellEject"
SWEP.TriggerDelay = .075
SWEP.CycleTime = .05
SWEP.Primary.Automatic = false
SWEP.ENT = "mann_ent_m16"
SWEP.CustomColor = Color(200, 200, 200, 255)
SWEP.HolsterSlot = 3
SWEP.AimPos = Vector(-1.9, -3, 1.5)
SWEP.AimAng = Angle(0, 1.05, 0)
SWEP.SprintPos = Vector(8, 2, -3)
SWEP.SprintAng = Angle(-10, 50, -10)
SWEP.CloseFireSound = Sound("weapons/firearms/rifle_win1892/win1892_fire_01.wav")
SWEP.ExtraFireSound = Sound("snd_mann_bulletcrack.wav")
SWEP.FarFireSound = Sound("weapons/firearms/mil_m16a4/m16_fire_01.wav")
SWEP.ReloadSound = Sound("snd_mann_pistol_reload3.wav")
SWEP.HandlingPitch = math.random(85, 90)
SWEP.ShotPitch = math.random(95, 100)
SWEP.DrawAnim = "draw"
SWEP.FireAnim = "fire1"
SWEP.LastFireAnim = "fire_last"
SWEP.DryFireAnim = "fire_dry"
SWEP.ReloadAnim = "reload_dry"
SWEP.ReloadTime = 3.5
SWEP.ReloadRate = 0.95
SWEP.HipHoldType = "alaln_smg_idle"
SWEP.AimHoldType = "alaln_smg_aim"
SWEP.DownHoldType = "passive"
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.BarrelLength = 9
SWEP.Droppable = true