AddCSLuaFile()
SWEP.Base = "mann_wep_base"
SWEP.PrintName = "Mosin Nagant M91"
SWEP.Purpose = "PLACEHOLDER" --!!
SWEP.Instructions = "LMB to fire,\nRMB to aim sights."
SWEP.Spawnable = true
SWEP.Category = "! Forsakened"
SWEP.Spawnable = true
SWEP.Primary.ClipSize = 5
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize
SWEP.ViewModel = Model("models/weapons/c_ins2_mosin_nagant.mdl")
SWEP.WorldModel = Model("models/weapons/w_ins2_mosin_nagant.mdl")
SWEP.IdlePos = Vector(0, -4, -1)
SWEP.ViewModelFOV = 90
SWEP.ViewModelFlip = false
SWEP.InsHands = false
SWEP.UseHands = true
SWEP.FuckedWorldModel = true
SWEP.FuckedWorldModelForward = 3
SWEP.FuckedWorldModelUp = -1.5
SWEP.Primary.Ammo = "357"
SWEP.Primary.Damage = 110
SWEP.Primary.Recoil = 4.1
SWEP.ShellType = ""
SWEP.Primary.Automatic = false
SWEP.TriggerDelay = .1
SWEP.CycleTime = 1.4
SWEP.CycleType = "manual"
SWEP.ReloadType = "individual"
SWEP.ENT = "mann_ent_mosin"
SWEP.CustomColor = Color(150, 150, 150, 255)
SWEP.HolsterSlot = 3
SWEP.AimPos = Vector(-3.1, -2, 2)
SWEP.AimAng = Angle(0, 0.5, 0)
SWEP.SprintPos = Vector(7, 5, 4)
SWEP.SprintAng = Angle(-20, 30, 0)
SWEP.CloseFireSound = Sound("weapons/firearms/hndg_sw686/revolver_fire_01.wav")
SWEP.ExtraFireSound = Sound("weapons/357_fire2.wav")
SWEP.FarFireSound = Sound("weapons/firearms/hndg_sw686/revolver_fire_01old.wav")
SWEP.ReloadSound = Sound("weapons/welrod/handling/welrod_boltback.wav")
SWEP.ShotPitch = math.random(95, 103)
SWEP.DrawAnim = "base_draw"
SWEP.FireAnim = "base_fire_start"
SWEP.DryFireAnim = "base_dryfire"
SWEP.ReloadAnim = "reload_start"
SWEP.InsertAnim = "reload_insert"
SWEP.AfterReloadAnim = "reload_end"
SWEP.CycleAnim = "base_fire_end"
SWEP.CycleSound = "weapons/firearms/rifle_sako85/sako_boltopen.wav"
SWEP.ReloadTime = 3.6
SWEP.ReloadRate = .9
SWEP.IconOverride = "editor/ai_goal_standoff"
SWEP.HipHoldType = "shotgun"
SWEP.AimHoldType = "rpg"
SWEP.DownHoldType = "passive"
SWEP.BarrelLength = 6
SWEP.Droppable = true